import 'dart:ui';

class ColorsManager {
  static const Color primaryWildBlueYonder = Color(0xFF7D8AC3);
  static const Color secondaryWildBlueYonder = Color(0xFF7E89B7);
  static const Color rangoonGreen = Color(0xFF1A1A1A);
  static const Color ironSideGrey = Color(0xFF666666);
  static const Color mercury = Color(0xFFE6E6E6);
  static const Color dune = Color(0xFF333333);
  static const Color liver = Color(0xFF4D4D4D);
  static const Color blueBell = Color(0xFF97A1CF);
  static const Color glaucous = Color(0xFF6B78AC);
  static const Color lemonGrass = Color(0xFF999999);
  static const Color softPeach = Color(0xFFEDEFF5);
  static const Color rockBlue = Color(0xFFA2AACA);
  static const Color blueJay = Color(0xFF384579);
  static const Color schoolBusYellow = Color(0xFFEBA61E);
  static const Color cadetBlue = Color(0xFFA4AED5);
  static const Color granite = Color(0xFF808080);
  static const Color plantation = Color(0xCC235347);
  static const Color titanWhite = Color(0xFFE8F1FF);
  static const Color ghostWhite = Color(0xFFF5F9FF);
  static const Color surfieGreen = Color(0xFF167F71);
  static const Color muleFawn = Color(0xFF964233);
  static const Color geyser = Color(0xFFD8DCED);
  static const Color cloudBurst = Color(0xFF2A345B);
  static const Color nobel = Color(0xFFB3B3B3);
  static const Color duskyBlue = Color(0xFF465697);
  static const Color darkJungleGreen = Color(0xFF1E1E1E);
  static const Color mountainMist = Color(0xFF979797);
  static const Color pastelGrey = Color(0xFFCCCCCC);
  static const Color catskillWhite = Color(0xFFF2F4F9);
  static const Color amethystSmoke = Color(0xFF8A96C9);
  static const Color aquaHaze = Color(0xFFF2F4F5);
  static const Color artyClickRed = Color(0xFFFF0000);
  static const Color waikawaGrey = Color(0xFF5967A2);
  static const Color silverChalice = Color(0xFFAEAEAE);
  static const Color porcelain = Color(0xFFF2F2F2);
  static const Color cloverGreen = Color(0xFF209D3D);
  static const Color magnolia = Color(0xFFF5F6FA);
  static const Color charcoalGrey = Color(0xFF3F3F3F);
  static const Color chambray = Color(0xFF3F4A7A);
  static const Color iron = Color(0xFFD0D5DD);
  static const Color blueBerry = Color(0xFF3F4D88);
}
